### ISSUE TITLE
Why are the events of type uint8[] and not of type uint64[]?

### ISSUE THREAD

**Issue by AndreasAZiegler** [berndpfrommer/event_array_msgs#1]
First of all thanks a lot for your work on the ```metavision_ros_driver```.

Since I read [here](https://discourse.ros.org/t/ros2-speed/20162/28) that you wrote:
>  I ended up squeezing all event data into a uint64 field and then essentially packing/unpacking manually into that 64bit space

I'm wondering why the events are stored in ```uint8[]``` and not in a ```uint64[]```?

**Comment by berndpfrommer** [comment]
For the current encoding of "mono" events this does look indeed nonsensical. But for other encodings down the road (e.g. color cameras) a 64 bit boundary may be awkward.
In fact from monitoring the USB bandwidth it appears that the event stream can be compressed to about 2-3 bits/event (during high load), much much better than the 64bits/event of this message representation.

**Comment by AndreasAZiegler** [comment]
Thanks for the clarification @berndpfrommer.
